### ISSUE TITLE
Create Actor & Create Item don't honor light mode setting

### ISSUE THREAD

**Issue by sirkerry** [jesuisfrog/AFMBE-Jesuisfrog-Unofficial#1]
The Create Actor and Create Item popups don't honor the Light Mode setting, the sheets do fine.

I find the black and dark gray text on the dark slate gray color very difficult to read:

![image](https://github.com/user-attachments/assets/47de057d-ff0b-498e-b631-6cda8dd034d9)

Could you please change it to a much lighter color? Also it would be nice if the Light Mode settings worked for the popups.

**Comment by jesuisfrog** [comment]
A big update is coming over the weekend that will resolve the issue.
