### ISSUE TITLE
BUG - Cannot create Weapon Item

### ISSUE THREAD

**Issue by InstantZzz** [jesuisfrog/AFMBE-Jesuisfrog-Unofficial#3]
Foundry V 12 Build - 328.
AFMBE by Jesuisfrog V 1.1.0

Go to ITEM tabs, select CREATE ITEM, choose WEAPON, get the following error: 
![image](https://github.com/user-attachments/assets/eab2a5c0-6862-4a5d-a4f1-6f9104f49e9c)

**Comment by jesuisfrog** [comment]
Good catch, I'll get on it as soon as I have some time.

**Comment by jesuisfrog** [comment]
Updating the system now, issue was resolved.
